"""add_index_to_trade_log

Revision ID: 1403e6d80d1d
Revises: a7dd10d9b220
Create Date: 2025-04-22 13:34:52.685449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "1403e6d80d1d"
down_revision: Union[str, None] = "a7dd10d9b220"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_trade_ticket_created_at"), "trade_ticket", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_ticket_created_at"), table_name="trade_ticket")
    # ### end Alembic commands ###
