"""add index to credit log

Revision ID: a7dd10d9b220
Revises: a0e430ed5341
Create Date: 2025-04-20 19:27:45.813462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "a7dd10d9b220"
down_revision: Union[str, None] = "a0e430ed5341"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_credit_log_created_at"), "credit_log", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credit_log_created_at"), table_name="credit_log")
    # ### end Alembic commands ###
